In [1]:
import tensorflow as tf
from tensorflow import keras
import sys
sys.path.append("../src")
from Ensemble import Ensemble, EnsembleMethods

2023-01-31 13:33:10.263108: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-31 13:33:10.388781: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-31 13:33:11.388523: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/bwhpc/common/devel/cuda/11.8/lib64
2023-01-31 13:33:11.388590: W tensorflow/compil

SyntaxError: invalid syntax (Ensemble.py, line 26)

In [2]:
model = keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(3,)),
    tf.keras.layers.Dense(3)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 12        
                                                                 
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


In [8]:
model2 = keras.Sequential([
    keras.layers.InputLayer(input_shape=(3,)),
    keras.layers.Dense(3),
    keras.layers.Dense(3)
])

model3 = keras.Sequential([
    keras.layers.InputLayer(input_shape=(3,)),
    keras.layers.Dense(5),
    keras.layers.Dense(3)
])

In [4]:
t = tf.random.normal((1,3))
t

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-1.4861596 ,  0.12685718,  0.75231695]], dtype=float32)>

In [9]:
model(t)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.54504836,  0.26238364,  0.31988698]], dtype=float32)>

In [11]:
ensemble = Ensemble([model, model2, model3], ensemble_type=EnsembleMethods.MAJORITY_VOTE)
ensemble(t)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.89691097, -0.3849231 ,  0.79965353], dtype=float32)>