In [1]:
import tensorflow as tf
import tensorflow.keras as keras

from Ensemble import Ensemble, EnsembleMethods

In [2]:
model = keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(3,)),
    tf.keras.layers.Dense(3)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 12        
                                                                 
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


In [8]:
model2 = keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(3,)),
    tf.keras.layers.Dense(3),
    tf.keras.layers.Dense(3)
])

model3 = keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(3,)),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(3)
])

In [4]:
t = tf.random.normal((1,3))
t

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-1.4861596 ,  0.12685718,  0.75231695]], dtype=float32)>

In [9]:
model(t)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.54504836,  0.26238364,  0.31988698]], dtype=float32)>

In [11]:
ensemble = Ensemble([model, model2, model3], ensemble_type=EnsembleMethods.MAJORITY_VOTE)
ensemble(t)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.89691097, -0.3849231 ,  0.79965353], dtype=float32)>